### ISSUE TITLE
none or only few documents are visible to the google api service

### ISSUE THREAD

**Issue by FTeichmann** [AKSW/googledoc-viewer#3]
After adding a new document to the folder there sometimes seems to be an issue that not all available (readable) documents are actually fetched by the php function although the authorization has not been modified.

We don't know what causes this yet but there is a simple workaround: Just touch the description of every file that should be readable for the service and add/delete whitespace.

**Comment by white-gecko** [comment]
@FTeichmann fixed the issue by using the workaround of touching all descriptions
